from __future__ import annotations

from pathlib import Path
from typing import Any

from korserver.config.models import AppConfig, GroupPolicyConfig
from korserver.renderers.base import TemplateRenderer


class OcservConfigRenderer(TemplateRenderer):
    def render(self, config: AppConfig) -> str:
        auth_lines: list[str] = []
        if config.auth.password.enabled:
            auth_lines.append(f"plain[passwd={config.secret_path('ocpasswd')}]")
        if config.auth.oidc.enabled:
            auth_lines.append(_oidc_auth_line(config))
        if config.auth.certificate.enabled:
            auth_lines.append("certificate")
        if config.auth.otp.enabled and config.auth.otp.ocserv_oath_auth:
            auth_lines.append(f"oath[usersfile={config.secret_path('users.oath')}]")

        if config.certificates.mode == "external":
            server_cert = config.certificates.server_cert
            server_key = config.certificates.server_key
            ca_cert = config.certificates.ca_cert
        else:
            server_cert = config.cert_path("server.crt")
            server_key = config.cert_path("server.key")
            ca_cert = config.cert_path("ca.crt")

        context: dict[str, Any] = {
            "config": config,
            "client_dns": config.client_dns_servers(),
            "dns_tunnel_active": config.dns_tunnel_active(),
            "auth_lines": auth_lines,
            "select_groups": _select_group_lines(config),
            "server_cert": server_cert,
            "server_key": server_key,
            "ca_cert": ca_cert,
            "occtl_socket_file": config.generated_path("occtl.sock"),
            "socket_file": config.system.generated_dir / "ocserv.sock",
        }
        return self.render_template("ocserv.conf.j2", context)

    def target_path(self, config: AppConfig) -> Path:
        return config.generated_path("ocserv.conf")

    def group_policy_target_path(self, config: AppConfig, group: GroupPolicyConfig) -> Path:
        group_dir = config.identity.config_per_group_dir or (
            config.system.generated_dir / "config-per-group"
        )
        return group_dir / group.name

    def render_group_policy(self, group: GroupPolicyConfig) -> str:
        lines = [
            "# Generated by korserver. Manual edits may be overwritten.",
            f"# Group policy: {group.name}",
        ]
        for item in group.routes:
            lines.append(f"route = {item}")
        for item in group.no_routes:
            lines.append(f"no-route = {item}")
        for item in group.dns:
            lines.append(f"dns = {item}")
        for item in group.split_dns:
            lines.append(f"split-dns = {item}")
        if group.tunnel_all_dns is not None:
            lines.append(f"tunnel-all-dns = {_bool_value(group.tunnel_all_dns)}")
        if group.max_same_clients is not None:
            lines.append(f"max-same-clients = {group.max_same_clients}")
        if group.session_timeout is not None:
            lines.append(f"session-timeout = {group.session_timeout}")
        if group.idle_timeout is not None:
            lines.append(f"idle-timeout = {group.idle_timeout}")
        if group.no_udp is not None:
            lines.append(f"no-udp = {_bool_value(group.no_udp)}")
        return "\n".join(lines) + "\n"


def _oidc_auth_line(config: AppConfig) -> str:
    oidc = config.auth.oidc
    if oidc.connector == "pam":
        options = [f"service={oidc.pam.service}"]
        if oidc.pam.gid_min is not None:
            options.append(f"gid-min={oidc.pam.gid_min}")
        return f"pam[{','.join(options)}]"
    if oidc.connector == "radius":
        options = [
            f"config={oidc.radius.config_file}",
            f"groupconfig={str(oidc.radius.groupconfig).lower()}",
            f"group-separator={oidc.radius.group_separator}",
        ]
        if oidc.radius.nas_identifier:
            options.append(f"nas-identifier={oidc.radius.nas_identifier}")
        return f"radius[{','.join(options)}]"
    return f"pam[service={oidc.pam.service}]"


def _select_group_lines(config: AppConfig) -> list[str]:
    return [
        f"{group.name}[{group.display_name}]"
        if group.display_name
        else group.name
        for group in config.identity.group_policies
    ]


def _bool_value(value: bool) -> str:
    return "true" if value else "false"
