from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from korserver.api import routes_users
from korserver.api.app import create_app
from korserver.config.models import AppConfig
from korserver.services.command import CommandError, CommandResult, CommandRunner
from korserver.services.users import UserConfig, UserService


class RecordingRunner(CommandRunner):
    def __init__(self) -> None:
        super().__init__()
        self.calls: list[tuple[str, ...]] = []

    def run(
        self,
        argv: Sequence[str],
        *,
        timeout: int = 30,
        cwd: str | None = None,
        input_text: str | None = None,
        env: Mapping[str, str] | None = None,
        check: bool = True,
        dry_run: bool = False,
        extra_secrets: Sequence[str] | None = None,
    ) -> CommandResult:
        del timeout, cwd, input_text, env, check, extra_secrets
        call = tuple(argv)
        self.calls.append(call)
        return CommandResult(call, 0, "", "", dry_run=dry_run)


def _config(tmp_path: Path) -> AppConfig:
    return AppConfig.model_validate(
        {
            "system": {
                "data_dir": tmp_path / "data",
                "generated_dir": tmp_path / "generated",
                "log_dir": tmp_path / "logs",
                "secrets_dir": tmp_path / "secrets",
            },
            "web": {"admin_password": "secret"},
        }
    )


def test_user_service_uses_ocpasswd_c_for_password_file(tmp_path: Path) -> None:
    runner = RecordingRunner()
    service = UserService(_config(tmp_path), runner=runner)

    service.create_user("alice", "password")
    service.change_password("alice", "new-password")
    service.disable_user("alice")
    service.enable_user("alice")

    passwd_file = str(tmp_path / "secrets" / "ocpasswd")
    assert runner.calls == [
        ("ocpasswd", "-c", passwd_file, "alice"),
        ("ocpasswd", "-c", passwd_file, "alice"),
        ("ocpasswd", "-c", passwd_file, "-l", "alice"),
        ("ocpasswd", "-c", passwd_file, "-u", "alice"),
    ]


def test_user_service_reads_ocpasswd_lock_and_artifact_state(tmp_path: Path) -> None:
    config = _config(tmp_path)
    passwd_file = config.secret_path("ocpasswd")
    passwd_file.parent.mkdir(parents=True)
    passwd_file.write_text("alice:hash:!locked\nbob:hash:active\n", encoding="utf-8")
    users_dir = config.system.data_dir / "certs" / "users"
    users_dir.mkdir(parents=True)
    (users_dir / "bob.crt").write_text("certificate", encoding="utf-8")
    (users_dir / "bob.p12").write_bytes(b"p12")

    users = {record.username: record for record in UserService(config).list_users()}

    assert users["alice"].disabled is True
    assert users["alice"].certificate_exists is False
    assert users["alice"].p12_exists is False
    assert users["bob"].disabled is False
    assert users["bob"].certificate_exists is True
    assert users["bob"].p12_exists is True


def test_user_service_writes_valid_per_user_config(tmp_path: Path) -> None:
    config = _config(tmp_path)
    service = UserService(config)

    result = service.save_user_config(
        "alice",
        UserConfig(
            dns=["1.1.1.1"],
            split_dns=["corp.example.com"],
            routes=["10.20.0.0/16"],
            no_udp=True,
            max_same_clients=1,
            restrict_user_to_ports="tcp(443), udp(443)",
        ),
    )

    assert config.identity.config_per_user_dir is not None
    path = config.identity.config_per_user_dir / "alice"
    assert result.returncode == 0
    assert path.read_text(encoding="utf-8") == (
        "# Generated by korserver. Manual edits may be overwritten.\n"
        "dns = 1.1.1.1\n"
        "split-dns = corp.example.com\n"
        "route = 10.20.0.0/16\n"
        "max-same-clients = 1\n"
        "restrict-user-to-ports = tcp(443), udp(443)\n"
        "no-udp = true\n"
    )
    assert service.read_user_config("alice").no_udp is True


@pytest.mark.parametrize("username", [".", ".."])
def test_dot_and_dotdot_usernames_are_rejected(tmp_path: Path, username: str) -> None:
    # Regression test: user_config_path() appends no filename suffix
    # (unlike cert/key paths, which do), so an unsanitized "." or ".."
    # would resolve to the per-user config directory itself or its parent
    # -- a path-traversal boundary violation even though it was previously
    # self-limiting (it lands on a directory, not a writable file).
    config = _config(tmp_path)
    service = UserService(config)

    with pytest.raises(ValueError, match="letters, numbers"):
        service.user_config_path(username)


def test_empty_per_user_config_deletes_file(tmp_path: Path) -> None:
    config = _config(tmp_path)
    service = UserService(config)
    service.save_user_config("alice", UserConfig(dns=["1.1.1.1"]))

    result = service.save_user_config("alice", UserConfig())

    assert result.returncode == 0
    assert not service.user_config_path("alice").exists()


def test_user_command_failure_returns_bad_request(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    class FailingUserService:
        def __init__(self, _config: AppConfig) -> None:
            pass

        def create_user(self, *_args: object, **_kwargs: object) -> CommandResult:
            result = CommandResult(("ocpasswd", "-c", "***"), 1, "", "ocpasswd failed")
            raise CommandError(result)

    monkeypatch.setattr(routes_users, "UserService", FailingUserService)
    client = TestClient(create_app(_config(tmp_path)))

    response = client.post(
        "/api/users",
        auth=("admin", "secret"),
        json={"username": "alice", "password": "password"},
    )

    assert response.status_code == 400
    assert response.json() == {"detail": "ocpasswd failed"}


def test_download_certificate_returns_the_crt_file(tmp_path: Path) -> None:
    config = _config(tmp_path)
    users_dir = config.system.data_dir / "certs" / "users"
    users_dir.mkdir(parents=True)
    (users_dir / "alice.crt").write_bytes(b"cert-bytes")
    client = TestClient(create_app(config))

    response = client.get("/api/users/alice/cert", auth=("admin", "secret"))

    assert response.status_code == 200
    assert response.content == b"cert-bytes"
    assert response.headers["content-disposition"] == 'attachment; filename="alice.crt"'


def test_download_certificate_404s_when_missing(tmp_path: Path) -> None:
    client = TestClient(create_app(_config(tmp_path)))

    response = client.get("/api/users/alice/cert", auth=("admin", "secret"))

    assert response.status_code == 404


def test_download_key_returns_the_key_file(tmp_path: Path) -> None:
    config = _config(tmp_path)
    users_dir = config.system.data_dir / "certs" / "users"
    users_dir.mkdir(parents=True)
    (users_dir / "alice.key").write_bytes(b"key-bytes")
    client = TestClient(create_app(config))

    response = client.get("/api/users/alice/key", auth=("admin", "secret"))

    assert response.status_code == 200
    assert response.content == b"key-bytes"
    assert response.headers["content-disposition"] == 'attachment; filename="alice.key"'


def test_download_key_404s_when_missing(tmp_path: Path) -> None:
    client = TestClient(create_app(_config(tmp_path)))

    response = client.get("/api/users/alice/key", auth=("admin", "secret"))

    assert response.status_code == 404
