from __future__ import annotations

from korserver.services.ocserv_reload import restart_only_settings, restart_required

BASE = """# Generated by korserver.
tcp-port = 443
listen-host = 0.0.0.0
device = vpns
max-clients = 128
auth = "plain[passwd=/secrets/ocpasswd]"
auth = "certificate"
"""


def test_restart_only_settings_ignores_reloadable_and_comments() -> None:
    assert restart_only_settings(BASE + '# auth = "pam"\nmax-same-clients = 2\n') == [
        ("tcp-port", "443"),
        ("listen-host", "0.0.0.0"),
        ("device", "vpns"),
        ("auth", '"plain[passwd=/secrets/ocpasswd]"'),
        ("auth", '"certificate"'),
    ]


def test_dropping_an_auth_method_requires_restart() -> None:
    current = BASE.replace('auth = "plain[passwd=/secrets/ocpasswd]"\n', "")
    assert restart_required(BASE, current)


def test_port_change_requires_restart() -> None:
    assert restart_required(BASE, BASE.replace("tcp-port = 443", "tcp-port = 8443"))


def test_reloadable_change_does_not_require_restart() -> None:
    assert not restart_required(BASE, BASE.replace("max-clients = 128", "max-clients = 64"))
