"""Point the host's own resolver at the built-in dnsmasq (routing.host_dns).

Domain-based host routing (routing.host_split domains, per-profile
host_domains, server-pushed split-DNS) only works when the host's lookups go
through dnsmasq: its nftset= directives are what fill the host nft sets, and
server-pushed domains must resolve through the upstream's DNS. Under
network_mode: host the container shares the host's network namespace but
not its files, so the host's resolver configuration is reached through a
bind mount:

- resolv_conf: /etc/resolv.conf -> /host/etc/resolv.conf. Rewritten in
  place (a bind-mounted file can't be replaced by rename), the original is
  kept in data_dir and restored when routing.host_dns is turned off, dnsmasq
  stops being needed, or the `host-dns-guard` supervisor program stops
  (container shutdown) -- the host must never be left pointing at a
  resolver that no longer runs. The guard also re-asserts the file when
  NetworkManager/DHCP rewrites it.
- resolved: /etc/systemd/resolved.conf.d -> /host/resolved.conf.d. A drop-in
  sends all host lookups to dnsmasq; systemd-resolved only reads it after
  `systemctl restart systemd-resolved` on the host, which the container
  cannot do itself.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from korserver.config.models import AppConfig
from korserver.services.files import FileManager

HOST_RESOLV_CONF = Path("/host/etc/resolv.conf")
HOST_RESOLVED_DIR = Path("/host/resolved.conf.d")
RESOLVED_DROPIN_NAME = "korserver.conf"
BACKUP_NAME = "host-resolv.conf.orig"
MARK = "# Generated by korserver"


@dataclass(frozen=True)
class HostDnsResult:
    mode: str
    changed: bool
    detail: str

    def as_dict(self) -> dict[str, object]:
        return {"mode": self.mode, "changed": self.changed, "detail": self.detail}


class HostDnsService:
    def __init__(
        self,
        config: AppConfig,
        files: FileManager | None = None,
        *,
        resolv_conf: Path = HOST_RESOLV_CONF,
        resolved_dir: Path = HOST_RESOLVED_DIR,
    ) -> None:
        self.config = config
        self.files = files or FileManager()
        self.resolv_conf = resolv_conf
        self.resolved_dir = resolved_dir

    @property
    def mode(self) -> str:
        return self.config.routing.host_dns

    @property
    def backup_path(self) -> Path:
        return self.config.system.data_dir / BACKUP_NAME

    @property
    def dropin_path(self) -> Path:
        return self.resolved_dir / RESOLVED_DROPIN_NAME

    def wanted(self) -> bool:
        return self.mode != "off" and self.config.dns_tunnel_active()

    def apply(self) -> HostDnsResult:
        """Bring the host resolver in line with the config (idempotent).

        Also undoes the other mode's leftovers, so switching modes or
        turning the feature off never leaves a stale redirect behind.
        """
        if not self.wanted():
            changed = self._restore_resolv_conf() | self._remove_dropin()
            reason = "off" if self.mode == "off" else "dnsmasq is not running"
            return HostDnsResult(self.mode, changed, f"host resolver untouched ({reason})")
        if self.mode == "resolv_conf":
            changed = self._remove_dropin()
            result = self._point_resolv_conf()
            return HostDnsResult(self.mode, changed or result.changed, result.detail)
        changed = self._restore_resolv_conf()
        result = self._write_dropin()
        return HostDnsResult(self.mode, changed or result.changed, result.detail)

    def restore(self) -> HostDnsResult:
        """Undo everything (container shutdown via host-dns-guard)."""
        changed = self._restore_resolv_conf()
        return HostDnsResult(
            self.mode,
            changed,
            "host resolv.conf restored" if changed else "nothing to restore",
        )

    def status(self) -> dict[str, object]:
        resolv_mounted = self.resolv_conf.exists()
        resolved_mounted = self.resolved_dir.is_dir()
        return {
            "mode": self.mode,
            "wanted": self.wanted(),
            "nameserver": self.config.internal_dns.listen,
            "resolv_conf_mounted": resolv_mounted,
            "resolv_conf_managed": resolv_mounted and self._ours(self._read(self.resolv_conf)),
            "resolved_dir_mounted": resolved_mounted,
            "resolved_dropin_present": self.dropin_path.exists(),
        }

    # --- resolv.conf ------------------------------------------------------

    def _desired_resolv_conf(self) -> str:
        return (
            f"{MARK}: host lookups go through the korserver dnsmasq.\n"
            f"# The original is kept in {self.backup_path} and restored when\n"
            "# korserver stops or routing.host_dns is turned off.\n"
            f"nameserver {self.config.internal_dns.listen}\n"
        )

    def _point_resolv_conf(self) -> HostDnsResult:
        if not self.resolv_conf.exists():
            return HostDnsResult(
                self.mode,
                False,
                f"{self.resolv_conf} is not mounted; add "
                f"'/etc/resolv.conf:{self.resolv_conf}' to the container volumes",
            )
        if self.config.internal_dns.port != 53:
            return HostDnsResult(
                self.mode,
                False,
                "resolv.conf can't name a port: internal_dns.port must be 53 "
                "(or use routing.host_dns: resolved)",
            )
        current = self._read(self.resolv_conf)
        desired = self._desired_resolv_conf()
        if current == desired:
            return HostDnsResult(self.mode, False, "host resolv.conf already points at dnsmasq")
        if not self._ours(current):
            # Whatever sits there now is the host's own configuration
            # (first run, or NetworkManager/DHCP rewrote it since): that is
            # what must come back on restore.
            self.files.atomic_write_text(self.backup_path, current)
        self._write_in_place(self.resolv_conf, desired)
        return HostDnsResult(self.mode, True, "host resolv.conf now points at dnsmasq")

    def _restore_resolv_conf(self) -> bool:
        if not self.resolv_conf.exists() or not self._ours(self._read(self.resolv_conf)):
            return False
        if not self.backup_path.exists():
            return False
        self._write_in_place(self.resolv_conf, self._read(self.backup_path))
        return True

    # --- systemd-resolved -------------------------------------------------

    def _desired_dropin(self) -> str:
        listen = self.config.internal_dns.listen
        port = self.config.internal_dns.port
        server = listen if port == 53 else f"{listen}:{port}"
        return (
            f"{MARK}: send all host DNS to the korserver dnsmasq.\n"
            "# Delete this file and restart systemd-resolved to undo.\n"
            "[Resolve]\n"
            # systemd appends list options across config files; the empty
            # assignment drops servers inherited from resolved.conf so
            # dnsmasq is the only global server.
            "DNS=\n"
            f"DNS={server}\n"
            "Domains=~.\n"
        )

    def _write_dropin(self) -> HostDnsResult:
        if not self.resolved_dir.is_dir():
            return HostDnsResult(
                self.mode,
                False,
                f"{self.resolved_dir} is not mounted; add "
                f"'/etc/systemd/resolved.conf.d:{self.resolved_dir}' to the container volumes",
            )
        desired = self._desired_dropin()
        if self.dropin_path.exists() and self._read(self.dropin_path) == desired:
            return HostDnsResult(self.mode, False, "systemd-resolved drop-in already in place")
        self.files.atomic_write_text(self.dropin_path, desired)
        return HostDnsResult(
            self.mode,
            True,
            f"wrote {self.dropin_path}; run `systemctl restart systemd-resolved` "
            "on the host to apply it",
        )

    def _remove_dropin(self) -> bool:
        if not self.dropin_path.exists() or not self._ours(self._read(self.dropin_path)):
            return False
        self.dropin_path.unlink()
        return True

    # --- helpers ----------------------------------------------------------

    @staticmethod
    def _ours(content: str) -> bool:
        return MARK in content

    @staticmethod
    def _read(path: Path) -> str:
        try:
            return path.read_text(encoding="utf-8")
        except OSError:
            return ""

    @staticmethod
    def _write_in_place(path: Path, content: str) -> None:
        # Not atomic on purpose: a bind-mounted file can't be replaced by
        # rename (EBUSY), only rewritten.
        with path.open("w", encoding="utf-8") as handle:
            handle.write(content)
