from __future__ import annotations

from typing import Any

DEFAULT_CONFIG: dict[str, Any] = {
    "system": {
        "timezone": "UTC",
        "data_dir": "/var/lib/korserver",
        "log_dir": "/var/log/korserver",
        "generated_dir": "/var/lib/korserver/generated",
        "secrets_dir": "/var/lib/korserver/secrets",
        "log_level": "info",
        "project_name": "korserver",
        "log_rotation": {
            "enabled": False,
            "max_size_mb": 50,
            "max_age": 0,
            "max_age_unit": "days",
            "keep_files": 5,
        },
    },
    "server": {
        "enabled": True,
        "listen": "0.0.0.0",
        "port": 443,
        "udp_enabled": True,
        "device": "vpns",
        "cn": "vpn.example.com",
        "realm": "Korvus VPN Server",
        "ipv4_network": "10.10.10.0/24",
        "dns": ["1.1.1.1", "8.8.8.8"],
        "search_domains": [],
        "routes": [],
        "no_routes": [],
        "max_clients": 128,
        "max_same_clients": 2,
        "keepalive": 32400,
        "compression": False,
        "cisco_client_compat": True,
        "camouflage": {"enabled": False, "secret": None, "realm": "Hidden service"},
        "connect_script": None,
        "disconnect_script": None,
        "debug_level": 2,
    },
    "certificates": {
        "mode": "auto",
        "ca_name": "Korvus Server CA",
        "server_cert": None,
        "server_key": None,
        "ca_cert": None,
        "letsencrypt": {
            "enabled": False,
            "email": None,
            "domains": [],
            "renew_reload": True,
            "auto_renew_enabled": True,
            "auto_renew_interval": 7,
            "auto_renew_interval_unit": "days",
            "http01_address": None,
            "http01_port": 80,
        },
    },
    "auth": {
        "password": {"enabled": True},
        "certificate": {"enabled": False},
        "otp": {
            "enabled": False,
            "ocserv_oath_auth": False,
            "issuer": "Korvus Server",
            "send_by_email": False,
            "send_by_telegram": False,
        },
    },
    "upstream": {
        "enabled": False,
        "interface": "oc-middle0",
        "active_profile": None,
        "check_interval": 5,
        "check_threshold": 3,
        "failover": False,
        "profiles": [],
    },
    "routing": {
        "mode": "full",
        "host_traffic": False,
        "host_mode": "full",
        "main_interface": "auto",
        "fwmark": "0x0c01",
        "table_id": 1201,
        "nft_prefix": "korserver",
        "split": {
            "tunnel_dns": False,
            "dnsmasq_listen": "10.10.10.1",
            "dnsmasq_port": 53,
            "routes_file": "/var/lib/korserver/routes.txt",
            "domains_file": "/var/lib/korserver/domains.txt",
            "routes": [],
            "domains": [],
        },
    },
    "internal_dns": {
        "enabled": False,
        "blocklist_domains": [],
        "blocklist_files": [],
        "blocklist_urls": [],
        "cache_size": 150,
        "log_queries": False,
        "local_records": [],
    },
    "web": {
        "enabled": False,
        "listen": "127.0.0.1",
        "port": 8443,
        "tls": True,
        "tls_cert": None,
        "tls_key": None,
        "allow_insecure_http": False,
        "trusted_proxies": [],
        "admin_user": "admin",
        "admin_password": None,
        "admin_password_hash": None,
        "static_dir": "/usr/share/korserver/frontend",
        "terminal_enabled": False,
        "terminal_idle_timeout": 900,
        "terminal_max_sessions": 2,
        "session_lifetime": 43200,
        "session_cookie_secure": True,
    },
    "cli": {"enabled": True},
    "advanced": {"raw_ocserv_options": []},
}
